# Generated by Django 5.0 on 2024-05-12 16:21

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rvm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='date_heure',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='statut',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='confirme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='motif',
            field=models.CharField(default=datetime.datetime(2024, 5, 12, 16, 21, 54, 282030, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_medecin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
