# Generated by Django 5.0 on 2024-05-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rvm', '0003_alter_rendezvous_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='user',
        ),
        migrations.AddField(
            model_name='medecin',
            name='disponibilites',
            field=models.CharField(default='Lundi - Vendredi, 08:00 - 17:00', max_length=255),
        ),
        migrations.AddField(
            model_name='medecin',
            name='nom',
            field=models.CharField(default='Nom par défaut', max_length=100),
        ),
        migrations.AddField(
            model_name='medecin',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
