# Generated by Django 5.0 on 2024-05-12 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rvm', '0005_alter_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='', max_length=277, verbose_name='Patient Email'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nom',
            field=models.CharField(default='', max_length=100, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_medecin', to='gestion_rvm.medecin'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_patient', to='gestion_rvm.patient'),
        ),
    ]
