# Generated by Django 5.0 on 2024-05-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rvm', '0006_remove_patient_adresse_remove_patient_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Medecin',
        ),
        migrations.DeleteModel(
            name='RendezVous',
        ),
    ]
