# Generated by Django 5.0 on 2024-05-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rvm', '0007_remove_rendezvous_medecin_remove_rendezvous_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100, verbose_name='Médecin Name')),
                ('email', models.EmailField(default='', max_length=277, verbose_name='Médecin Email')),
                ('specialite', models.CharField(max_length=100, verbose_name='Spécialité')),
            ],
        ),
    ]
