# Generated by Django 5.0 on 2024-05-13 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rvm', '0008_medecin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date du rendez-vous')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_rvm.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_rvm.patient')),
            ],
        ),
    ]
